### ISSUE TITLE
mvn compile throws errors

### ISSUE THREAD

**Issue by mahuntington** [spring-guides/gs-maven#21]
Hello,

I'm working on this guide, but when I run `mvn compile` I get the following error:

```
[ERROR] Source option 1.5 is no longer supported. Use 1.6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
```

I'm on OS X.  `mvn -v` shows:

```
Maven home: /Users/matthuntington/Desktop/apache-maven-3.5.0
Java version: 9, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```

`echo $JAVA_HOME` shows:

```
/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
```

`echo $PATH` shows:

```
/Users/matthuntington/Desktop/apache-maven-3.5.0/bin/:/Users/matthuntington/.rbenv/bin:/Users/matthuntington/.rbenv/shims:/Users/matthuntington/anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
```

any suggestions?  Thanks!

**Comment by mahuntington** [comment]
Solution: I added

```xml
<properties>
    <maven.compiler.source>1.6</maven.compiler.source>
    <maven.compiler.target>1.6</maven.compiler.target>
  </properties>
```

inside the project tag in pom.xml

**Comment by timlee1** [comment]
Can you explain the reason of the error? I also get the same error.

Why does your solution solve the problem?

Thanks.

**Comment by mahuntington** [comment]
I think the latest version of maven doesn’t support 1.5 anymore. You have to explicitly tell it which version to compile to. Not entirely sure, though.

**Comment by strzelaczinho** [comment]
mahuntington great solution . Just add in pom 

<properties>
    <maven.compiler.source>1.6</maven.compiler.source>
    <maven.compiler.target>1.6</maven.compiler.target>
  </properties>

and it will compile

**Comment by vm137** [comment]
worked for me.
thanks

**Comment by bilalyldz** [comment]
<properties>
<maven.compiler.source>1.6</maven.compiler.source>
<maven.compiler.target>1.6</maven.compiler.target>
 </properties>  
It is actually working but you have to be careful where to add it. You need to ad it inside the Properties without tags (open-close)

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-maven/commit/c2bf5536ea4163b63faeb9c76686759b86893a0c

**Comment by YaponEran** [comment]
@strzelaczinho 
worked for me, easy solution ))

**Comment by YaponEran** [comment]
@strzelaczinho worked, thank you for an easy solution

**Comment by sravankumar4** [comment]
Worked for me. thanks, Matt Huntington for an easy solution.

**Comment by amitbpal** [comment]
@mahuntington thanks it works for me.

**Comment by nitishpandey** [comment]
Worked like a charm. The error message that i got though is updated in 2018 :) 
Source option 5 is no longer supported. Use 6 or later.
I wonder why someone doesn't just make it switch to 1.6 on it's own when 1.5 was hard wired into it.

**Comment by Favorskij** [comment]
Use JavaServlet 3.0-alpha-1
https://mvnrepository.com/artifact/javax.servlet/servlet-api/3.0-alpha-1

```
<!-- https://mvnrepository.com/artifact/javax.servlet/servlet-api -->
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>servlet-api</artifactId>
    <version>3.0-alpha-1</version>
    <scope>provided</scope>
</dependency>

```

**Comment by fastestonakinapass** [comment]
has to be added after the name tag

**Comment by plao** [comment]
Many thanks @mahuntington !!!

**Comment by lkamal** [comment]
Solution from @mahuntington resolved it.

**Comment by ltlombardi** [comment]
One thing everyone missed to explain for the newbies:
When the error states that "version 5 or 1.5" isn't supported, it's sayinf that the JDK java developer kit version 1.5 isn't supported. User version 1.6 or latter.

**Comment by matthiasdenu** [comment]
Thanks. Yeah, I'm glad I read on to see your comment. The error message makes a lot more sense now. I thought version 5 or 1.5 had something to do with Maven. I didn't realize it was talking about which version of Java the project was being compiled to.

**Comment by aliasgarbaldiwalagartner** [comment]
<properties>
<maven.compiler.source>1.6</maven.compiler.source>
<maven.compiler.target>1.6</maven.compiler.target>
 </properties>

Worked for me!

**Comment by philipwhiuk** [comment]
> Worked like a charm. The error message that i got though is updated in 2018 :)
> Source option 5 is no longer supported. Use 6 or later.
> I wonder why someone doesn't just make it switch to 1.6 on it's own when 1.5 was hard wired into it.

Because this would change the behaviour silently which would be less obvious a problem.

**Comment by bastibaumi** [comment]
worked for me. Thanks for the solution.

**Comment by afincher** [comment]
I'm new to maven, but am I missing something, or is this solution to modify each individual maven project POM.XML file?
Please tell me that there is there somewhere a central XML file that we're editing to solve this problem for all projects going forward?

**Comment by JaimeCosteira** [comment]
Hello, I've got the same error and the solution worked.
Thank you very much.

**Comment by peterwillcn** [comment]
<properties>
      <maven.compiler.source>1.8</maven.compiler.source>
      <maven.compiler.target>1.8</maven.compiler.target>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

**Comment by AhmadHamed** [comment]
I had a similar problem:
source option 6 is no longer supported use 7 or later
target option 6 is no longer supported use 7 or later

this snippet solved it for me
`<properties>
  <maven.compiler.source>1.8</maven.compiler.source>
  <maven.compiler.target>1.8</maven.compiler.target>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>`

add it in the pom.xml, properties section

**Comment by franka107** [comment]
It's working for me too, thank you

**Comment by e-remington-lee** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <properties>
        <maven.compiler.source>6</maven.compiler.source>
        <maven.compiler.target>6</maven.compiler.target>
    </properties>
    <modelVersion>4.0.0</modelVersion>


    <groupId>com.list</groupId>
    <artifactId>toDoList</artifactId>
    <version>1.0-SNAPSHOT</version>


</project>

My project code looks like this and I am still getting:
Error:java: Source option 5 is no longer supported. Use 6 or later. (earlier someone said option 5 meant option 1.5)

**Comment by manoripriyadarshani** [comment]
> Can you explain the reason of the error? I also get the same error.
> 
> Why does your solution solve the problem?
> 
> Thanks.

The reason for the error: maven compiler is a plugin inside the maven system. In the compile life cycle phase, maven takes the java version as configured in maven compiler plugin in the pom.  When we have not specified the compiler plugin in the pom it takes the default compiler plugin which comes with maven versions. (eg: maven 2 comes with compiler version 1.4) If we want to use the latest java version at compile time need to provide it as follows

<properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

**Comment by e-remington-lee** [comment]
I believe I resolved this myself, it was unrelated to the posted solution
but more on my end.

Thanks for following up though!

**Comment by manojdjayz** [comment]
> Use JavaServlet 3.0-alpha-1
> https://mvnrepository.com/artifact/javax.servlet/servlet-api/3.0-alpha-1
> 
> ```
> 
> <dependency>
>     <groupId>javax.servlet</groupId>
>     <artifactId>servlet-api</artifactId>
>     <version>3.0-alpha-1</version>
>     <scope>provided</scope>
> </dependency>
> ```

Worked for "Source option 5 is no longer supported. Use 6 or later" when using InteliJ for Cucumber test automation

**Comment by wojtekDrozd** [comment]
I had this problem and didn't need to add anything to pom.xml. Just make sure that IDE compiler is set to appropriate version. Also check in project preferences that language level and SDK are set to appropriate version.

**Comment by ankit-suthar** [comment]
> Solution: I added
> 
> ```
> <properties>
>     <maven.compiler.source>1.6</maven.compiler.source>
>     <maven.compiler.target>1.6</maven.compiler.target>
>   </properties>
> ```
> 
> inside the project tag in pom.xml

Works for me.
Thanks a lot!

**Comment by larvavral** [comment]
@mahuntington Thanks for solution

**Comment by NaelsonDouglas** [comment]
> Solution: I added
> 
> ```
> <properties>
>     <maven.compiler.source>1.6</maven.compiler.source>
>     <maven.compiler.target>1.6</maven.compiler.target>
>   </properties>
> ```
> 
> inside the project tag in pom.xml

Worked!
Thanks
