### ISSUE TITLE
mvn package fails for demo build

### ISSUE THREAD

**Issue by orenwf** [spring-guides/gs-maven#23]
Figured this one our myself.

Was getting the following error when using `mvn package`

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:2.6:jar (default-jar) on
project gs-spring-boot: Execution default-jar of goal org.apache.maven.plugins:maven-jar- 
plugin:2.6:jar failed: An API incompatibility was encountered while executing 
org.apache.maven.plugins:maven-jar-plugin:2.6:jar: java.lang.ExceptionInInitializerError: null
```

I don't know exactly what caused it to be looking for an apparently incompatible version of the `maven-jar-plugin-2.6.jar`  however simply adding the following under plugins in pom.xml fixed the issue.

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <version>3.0.0</version>
</plugin>
```

**Comment by CODYSMAN** [comment]
> Figured this one our myself.
> 
> Was getting the following error when using `mvn package`
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:2.6:jar (default-jar) on
> project gs-spring-boot: Execution default-jar of goal org.apache.maven.plugins:maven-jar- 
> plugin:2.6:jar failed: An API incompatibility was encountered while executing 
> org.apache.maven.plugins:maven-jar-plugin:2.6:jar: java.lang.ExceptionInInitializerError: null
> ```
> 
> I don't know exactly what caused it to be looking for an apparently incompatible version of the `maven-jar-plugin-2.6.jar` however simply adding the following under plugins in pom.xml fixed the issue.
> 
> ```
> <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-jar-plugin</artifactId>
>     <version>3.0.0</version>
> </plugin>
> ```

That really fixes the problem. Probably the reason is that in version 3.0.0 they just fixed the issue on the library level.

**Comment by dsyer** [comment]
Works for me. Tried with Java 11 and 8.

**Comment by jackila** [comment]
i think it is caused by the version of maven

**Comment by dsyer** [comment]
Could be. Please use the wrapper supplied (./mvnw).

**Comment by dsyer** [comment]
Actually the wrapper is in the examples but not mentioned in the guide text. Maybe we should fix that instead?
