### ISSUE TITLE
shade plugin: avoiding "Invalid signature"

### ISSUE THREAD

**Issue by stash** [spring-guides/gs-maven#7]
As described [in this blog post](http://zhentao-li.blogspot.com/2012/06/maven-shade-plugin-invalid-signature.html), if you try to include a `jarsigner`-signed dependency, you get a nasty "Invalid signature file digest for Manifest main attributes" stacktrace.

The blog above suggests adding the following snippet to the shade plugin `<configuration>` section.

``` xml
          <filters>
            <filter>
              <artifact>*:*</artifact>
              <excludes>
                <exclude>META-INF/*.SF</exclude>
                <exclude>META-INF/*.DSA</exclude>
                <exclude>META-INF/*.RSA</exclude>
              </excludes>
            </filter>
          </filters>
```

I'm new to Maven and Shade, so I'm not sure what the security implications of doing this are, but I thought I should suggest it.  Thanks for writing the guide; i found it very useful.

**Comment by wengm** [comment]
Does that configuration work for you? I doesn't work for me. The generated jar file still contains signature files and when I try to run `jarsigner -verify jarfileName` it will print out the error message "`java.lang.SecurityException: Invalid signature file digest for Manifest main attributes`".

@stash how did you do in your environment?
